# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  - name: Skills
    url: '#skills'
    weight: 20
  - name: Experience
    url: '#excperience'
    weight: 30
  - name: Projects (ETIS)
    #url: '#projects'
    url: 'https://www.etis.ee/CV/Uku_Vainik/est?tabId=Projects&lang=ENG'
    weight: 40
  - name: Publications (Google Scholar)
    url: 'https://scholar.google.com/citations?user=ouXTgzIAAAAJ&hl=en'
#    url: '#featured'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
